config/routes.rb
Rails.application.routes.draw do
  get "/customers", to: "customers#index"
  get "/customers/new", to: "customers#new"
  post "/customers", to: "customers#create"
  get "/customers/:id/update", to: "customers#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  render @articles
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController


  # GET /customers
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end
  def edit
    @customer = Customer.find(params[:id])
  end



  def create
    @customers = Customer.new(params.permit(:name, :email, :phone))
    if @customers.save
      redirect_to customers_path
    else
      render :new
    end
  end
  def update
    @customers = Customer.find(params[:id])
    if @customers.update(params.permit(:name, :email, :phone))
      redirect_to customers_path
    else
      render :edit
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Table Customer</h2>
  <a href="/customers/new"  class="btn btn-primary">Add Customer </a>
  <table class="table">
    <thead>
    <tr>
      <th>Id</th>
      <th >Name</th>
      <th >Email</th>
      <th >Phone</th>
      <th >Action</th>
    </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone %></td>
        <td>
          <a href="/customers/<%= customer.id %>/update"  class="btn btn-primary"> Edit </a>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

</body>
</html>

app/views/customers/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%=csrf_meta_tags %>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h2>Create Customer</h2>
  <form method="post" action="/customers">

    <div class="form-group">
      <label for="name">Name:</label>
      <input type="text" class="form-control" id="name" name="name">
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
      <label for="phone">Phone:</label>
      <input type="text" class="form-control" id="phone" name="phone">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>